twitter_backend/accounts/urls.py
from django.urls import path

# App imports
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view, name='login'),
    path('logout',views.logout_view,name='logout'), 
    path('register/',views.register_view,name='register'),
    path('home/',views.HomePageView.as_view(),name='home'),
    path('profile/',views.ProfilePageView.as_view(),name='profile'),
    path('profile/<int:profile_id>/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('edit-profile/', views.EditProfileView.as_view(), name='edit-profile'),
    path('follow/<int:pk>/',views.FollowUser.as_view(),name="follow"),
    path('create-tweet/',views.CreateTweetView.as_view(),name="create-tweet"),
    path('increment-like/<uuid:tweet_uuid>/', views.IncrementLikeView.as_view(), name='increment_like'),
    path('add-comment/<uuid:tweet_uuid>/', views.AddCommentAPIView.as_view(), name='add-comment'),
    path('retweet/<uuid:tweet_uuid>/', views.RetweetAPIView.as_view(), name='retweet'),
    path('bookmark/<uuid:tweet_uuid>/', views.BookmarkAPIView.as_view(), name='bookmark-detail'),
    path('bookmark',views.BookmarkDetailView.as_view(),name='bookmark'),
    path('profile/api/delete-post/<uuid:tweet_uuid>/', views.DeletePostAPIView.as_view(), name='delete-post'),
    path('profile/api/get-tweet/<uuid:tweet_uuid>/', views.get_tweet, name='get-tweet'),
    path('update-tweet/<uuid:tweet_uuid>/',views.UpdateTweetView.as_view(),name='update-tweet'),
    path('home/single-tweet/<uuid:tweet_uuid>/', views.TweetDetailView.as_view(), name='single_tweet'),

]   

twitter_backend/twitter_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',
        include([
            path('', include('accounts.urls')),
        ])
    )
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter_backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

import uuid

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='profile')
    coverImage = models.ImageField(null=True, blank=True)
    profileImage = models.ImageField(null=True,blank=True)
    bio = models.TextField(max_length=160, blank=True, null=True)
    display_name = models.CharField(max_length=30, blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    is_verified = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.user.username)
    
    def get_absolute_url(self):
        return reverse("profile_detail", kwargs={"username": self.user.username})
    
    def create_profile(sender,instance,created,**kwargs):
        if created:
            user = UserProfile(user=instance)
            user.save()
    models.signals.post_save.connect(create_profile,sender=User)

class Followers(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    following = models.ManyToManyField(to=User, related_name="following", blank=True)
    followers = models.ManyToManyField(to=User, related_name="followed_user", blank=True)
    def create_follow(sender,instance,created,**kwargs):
        if created:
            user = Followers(user=instance)
            user.save()
    models.signals.post_save.connect(create_follow,sender=User)


class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    uuid = models.UUIDField(default=uuid.uuid4, max_length=40, unique=True, editable=False)
    content = models.TextField(max_length=240, blank=False, null=False)
    media = models.FileField(upload_to='tweet-media', blank=True, null=True)
    likes = models.ManyToManyField(to=User, blank=True, related_name='tweet_likes')
    is_video = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now_add=True)

class TweetComments(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    tweet = models.ForeignKey(to=Tweet, on_delete=models.CASCADE,related_name='comment')
    comment_content = models.TextField(max_length=200, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    media = models.ImageField(upload_to='comment-media', blank=True, null=True)
    likes = models.ManyToManyField(User, blank=True, related_name='comment_likes')


class TweetRetweet(models.Model):
    user =  models.ForeignKey(to=User, on_delete=models.CASCADE)
    retweet = models.ForeignKey(Tweet,on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now_add=True)


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    

twitter_backend/accounts/forms.py
# from django import forms 
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User


# class LoginForm(forms.Form):
#     username = forms.CharField()
#     password = forms.CharField(widget=forms.PasswordInput)   

# class SignUpForm(UserCreationForm):
    
#     email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1']
from django import forms
from .models import UserProfile, Tweet

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'display_name', 'profileImage']

twitter_backend/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect,JsonResponse

# rest framework
from rest_framework.response import Response
from rest_framework.decorators import api_view, renderer_classes
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated     

# App imports
from  . import serializers
from .models import Tweet, UserProfile, TweetRetweet, Bookmark

@api_view(['GET', 'POST'])
@renderer_classes([TemplateHTMLRenderer])
def register_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('accounts:home'))

    if request.method == 'POST':
        serializer = serializers.RegistrationSerializer(data=request.data)  
        if serializer.is_valid():
            username = serializer.validated_data['username']
            password = serializer.validated_data['password']
            email = serializer.validated_data['email']
 
            user = User.objects.create(username=username, email=email)
            user.set_password(password)
            user.save()
            return Response({"message": "Successfully registered"},template_name='accounts/login.html')
        else:
            return Response({"error": "username is already taken"}, template_name='accounts/register.html')
            
    return Response({"serializer": serializers.RegistrationSerializer()}, template_name='accounts/register.html')


@api_view(['GET', 'POST'])
@renderer_classes([TemplateHTMLRenderer])    
def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('accounts:home'))

    if request.method == 'POST':
        serializer = serializers.LoginSerializer(data=request.data)
        if serializer.is_valid():
            username = serializer.validated_data['username']
            password = serializer.validated_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('accounts:home'))
            else:
                return Response({"error": "Invalid credentials"}, template_name='accounts/login.html')

    return Response({"serializer": serializers.LoginSerializer()}, template_name='accounts/login.html')

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))

class HomePageView(APIView):
    authentication_classes = [SessionAuthentication]
    def get(self, request, format=None):
        if request.user.is_anonymous:
            return HttpResponseRedirect(reverse('accounts:login')) 
        queryset = Tweet.objects.exclude(user=request.user).order_by('-updated_at')
        serializer = serializers.TweetSerializer(queryset, many=True)
        current_user = UserProfile.objects.get(user = request.user)
        user_serializer = serializers.UserProfileSerializer(current_user)
        return render(
            request, 
            'accounts/home.html',
            { 
                'logged_user' : user_serializer.data,
                'tweets': serializer.data,
            }
        )

class ProfilePageView(APIView):
    authentication_classes = [SessionAuthentication]
    def get(self,request,format = None):
        queryset = Tweet.objects.filter(user = request.user).order_by('-updated_at')
        serializer = serializers.TweetSerializer(queryset, many=True)
        current_user = UserProfile.objects.get(user = request.user)
        user_serializer = serializers.UserProfileSerializer(current_user)
        return render(
            request, 
            'accounts/profile.html',
            {   'logged_user' : user_serializer.data,
                'tweets': serializer.data,
                'posts': queryset,
                'following':request.user.followers.following.all(),
                'followers':request.user.followers.followers.all(),
                'retweets':TweetRetweet.objects.filter(user=request.user),
            }
        )

class EditProfileView(APIView):
    authentication_classes = [SessionAuthentication]
    def post(self, request, format = None):
        user_profile = request.user.profile  
        serializer = serializers.UserProfileSerializer(user_profile, data=request.data )
        if serializer.is_valid():
            serializer.save()
        return HttpResponseRedirect(reverse('accounts:profile'))

class CreateTweetView(APIView):
    authentication_classes = [SessionAuthentication]
    def post(self, request, *args, **kwargs):
        serializer = serializers.TweetSaveSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user)
        return HttpResponseRedirect(reverse('accounts:profile')) 


class IncrementLikeView(APIView):
    authentication_classes = [SessionAuthentication]
    def post(self, request, tweet_uuid, *args, **kwargs):
        tweet = get_object_or_404(Tweet, uuid=tweet_uuid)
        if request.user not in tweet.likes.all():
            tweet.likes.add(request.user)
        else:
            tweet.likes.remove(request.user)
        likes_count = tweet.likes.count()
        return JsonResponse({'likes_count': likes_count})


class ProfileDetailView(APIView):
    template_name = 'accounts/profile.html'
    authentication_classes = [SessionAuthentication]
    def get(self, request, profile_id):
        user_profile = UserProfile.objects.get(id=profile_id)    
        queryset = Tweet.objects.filter(user = user_profile.user).order_by('-updated_at')
        serializer = serializers.TweetSerializer(queryset, many=True)
        user_serializer = serializers.UserProfileSerializer(user_profile)
        
        current_user = UserProfile.objects.get(user = request.user)
        curent_user_serializer = serializers.UserProfileSerializer(current_user)
        
        profile_user_follow = request.user.followers
        current_user_follow = user_profile.user.followers

        is_following = user_profile.user in  request.user.followers.following.all()
    
        return render(
            request,
            'accounts/others-profile.html',
            {   
                'posts' : queryset,
                'following':current_user_follow.following.all(),
                'followers':current_user_follow.followers.all(),
                'is_following':is_following,
                'profile_id':profile_id,
                'logged_user' : curent_user_serializer.data ,
                'specific' : user_serializer.data,
                'tweets': serializer.data,
                'retweets':TweetRetweet.objects.filter(user=user_profile.user)
            }
        )

class FollowUser(APIView):
    authentication_classes = [SessionAuthentication]
    
    def post(self, request,pk):
        user_to_toggle = User.objects.get(id=pk)
        current_user = request.user
        current_user_profile = request.user.followers
        user_to_toggle_profile = user_to_toggle.followers
        
        is_following = current_user_profile.following.filter(username = user_to_toggle.username).exists()

        if is_following:
            current_user_profile.following.remove(user_to_toggle)
            user_to_toggle_profile.followers.remove(current_user)
            
        else:
            current_user_profile.following.add(user_to_toggle)
            user_to_toggle_profile.followers.add(current_user)

        return JsonResponse(
            {
                'is_following': not is_following,
                'following':user_to_toggle_profile.following.count(),
                'followers':user_to_toggle_profile.followers.count(),
            })

class AddCommentAPIView(APIView):
    def post(self, request, tweet_uuid, *args, **kwargs):
        tweet = get_object_or_404(Tweet, uuid=tweet_uuid)
        serializer = serializers.CommentSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user, tweet=tweet)
        return HttpResponseRedirect(reverse('accounts:home'))

class RetweetAPIView(APIView):
    def post(self, request, *args, **kwargs):
        serializer = serializers.RetweetSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        tweet_uuid = serializer.validated_data['tweet_uuid']

        tweet = get_object_or_404(Tweet, uuid=tweet_uuid)

        if TweetRetweet.objects.filter(user=request.user, retweet=tweet).exists():
            TweetRetweet.objects.filter(user=request.user, retweet=tweet).delete()
            retweet_status = False
        else:
            TweetRetweet.objects.create(user=request.user, retweet=tweet)
            retweet_status = True
        return Response(
            {
                'retweet_status': retweet_status,
            }, status=status.HTTP_200_OK)


class BookmarkAPIView(APIView):
    def post(self, request,tweet_uuid, *args, **kwargs):
        user = request.user  
        tweet = get_object_or_404(Tweet, uuid=tweet_uuid)
        
        if Bookmark.objects.filter(user=user, tweet=tweet).exists():
            existing_bookmark = Bookmark.objects.get(user=user, tweet=tweet)
            existing_bookmark.delete()
            return JsonResponse({'success': False, 'message': 'Bookmark deleted'})

        # Create the bookmark
        bookmark = Bookmark(user=user, tweet=tweet)
        bookmark.save()

        return JsonResponse({'success': True})

class BookmarkDetailView(APIView):
    def get(self, request):
        queryset = Tweet.objects.filter(bookmark__user=request.user)

twitter_backend/accounts/templates/accounts/comments.html
{% extends "accounts/home.html" %}
{% load static %}

{% block header-profile %}

{% endblock header-profile %}

{% block main-user-tweet %}

{% endblock %}


{% block tweets %}
<div class="other-tweets-container">
    <div class="other-tweets">
        <div class="tweeter">
            <div class="tweeter-profile">
                <img src="{{ tweet.user_profile.profileImage }}" alt="profie picture" />
                <div class="tweeter-name">
                    <diV>
                        <a href="{% url 'accounts:profile-detail' profile_id=tweet.user_profile.id %}">
                            <p>
                                <span class="tweeter-account">{{ tweet.user_profile.display_name }}
                                </span>
                                <span class="freecodecamp-badge"><img src="{% static 'images/verified.svg' %}"
                                        alt="verification-badge" /></span>
                                <span class="tweeter-username">@{{ tweet.user_profile.display_name }}
                                </span>
                                <span>{{ tweet.updated_at.datetime }}</span>
                            </p>
                        </a>
                    </diV>

                    {% block more-icon %}
                    {% endblock %}
                </div>
            </div>

            <div class="tweet">
                <div class="tweet-details">
                    <div>
                        <div class="click-for-comments" id="tweet-comments-{{tweet.uuid}}">
                            <div class="tweet-text">
                                <p class="tweet-text">
                                    {{ tweet.content }} </p>
                            </div>
                            {% if tweet.media %}
                            <div class="tweet-image">
                                <img src="{{ tweet.media }}" alt="{{ tweet.user_profile.display_name.username }}" />
                                <div class="tweet-image-caption">
                                    <p>@{{ tweet.user_profile.display_name }}</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        <div class="tweet-reactions-2">
                            <div class="replies">
                                <div class="tweet-replies" style="cursor: pointer;">
                                    <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 0 24 24" aria-hidden="true"
                                        class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi"
                                        width="20" height="20">
                                        <g fill="currentColor">
                                            <path
                                                d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z">
                                            </path>
                                        </g>
                                    </svg>
                                </div>
                                <div class="statistics">
                                    {{ tweet.comments|length }}
                                </div>
                            </div>

                            <div class="retweets">
                                <div class="retweet-button" id="retweet-button{{tweet.uuid}}"
                                    data-retweet-id="{{ tweet.uuid }}">
                                    <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 0 24 24" aria-hidden="true"
                                        class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi"
                                        width="20" height="20">
                                        <g fill="currentColor">
                                            <path
                                                d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z">
                                            </path>
                                        </g>
                                    </svg>
                                </div>
                                <div class="statistics">
                                    <p id="retweet-count">{{ tweet.retweets|length }}</p>
                                </div>
                            </div>

                            <div class="likes">
                                <div class="like-button" data-tweet-id="{{ tweet.uuid }}" style="cursor: pointer;">
                                    <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 0 24 24" aria-hidden="true"
                                        class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi"
                                        width="20" height="20">
                                        <g fill="currentColor">
                                            <path
                                                d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12zM7.354 4.225c-2.08 0-3.903 1.988-3.903 4.255 0 5.74 7.034 11.596 8.55 11.658 1.518-.062 8.55-5.917 8.55-11.658 0-2.267-1.823-4.255-3.903-4.255-2.528 0-3.94 2.936-3.952 2.965-.23.562-1.156.562-1.387 0-.014-.03-1.425-2.965-3.954-2.965z">
                                            </path>
                                        </g>
                                    </svg>
                                </div>
                                <div class="statistics">
                                    {{ tweet.likes|length }}
                                </div>
                            </div>

                            <div class="bookmark">
                                <div class="bookmark-icon" style="cursor:pointer" data-bookmark-id="{{ tweet.uuid }}">
                                    <img src="{% static 'images/bookmarks.svg' %}" alt="bookmarks icon"
                                        style="height:20;width:20;" />
                                </div>
                                <div class="statistics">
                                    {{tweet.bookmarks|length }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tweet-comments">
        {% for comment in tweet.comments %}
            {{ comment.comment_content }}
        {% endfor %}
    </div>
    <div class="user-tweet">
        <form id="commentForm" action="{% url 'accounts:add-comment' tweet_uuid=tweet.uuid %}" method="post">
            {% csrf_token %}
            <div class="tweet-input-section">
                <div class="shiva-profile img-2">
                    <img src="{{ logged_user.profileImage }}" alt="shiva's profile" />
                </div>
                <div class="tweet-input">
                    <input type="text" class="tweet-input-button" placeholder="whats's happening"
                        name="comment_content">
                </div>
            </div>
            <div class="edit-tools">
                <div class="tools-wrapper">
                    <div class="tools">
                        <label for="image"><img src="{% static 'images/media.svg' %}"
                                alt="media icon" /></label>
                        <input type="file" id="image" name="media" accept="image/*">
                    </div>
                </div>
                <div>
                    <button class="post-tweet" type="submit">Tweet</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

twitter_backend/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="https://img.icons8.com/color/48/000000/twitter.png">
    <title>{% block title %}Log in to Twitter{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    {% block styles %}{% endblock %}
  </head>
  <body>
    {% block body %}
      <div class="container">
        <div class="header">
          <img src="https://img.icons8.com/color/48/000000/twitter.png" alt="Twitter Logo">
          <h2>Log in to Twitter</h2>
        </div>
        <div class="error">
          {% if error %}
              <p>{{error}}</p>
            {% endif %}
        </div>
        <div class="message">
          {% if message %}
            <p>{{message}}</p>
          {% endif %}
        </div>
        <div class="form">
          <form method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Phone, email, or username">
            <input type="password" name="password" placeholder="Password">
            <button type="submit">Log in</button>
          </form>
        </div>
      
        <div class="footer">
          <a href="#">Forgot password?</a> · <a href="{% url 'accounts:register' %}">Sign up for Twitter</a>
        </div>
      </div>
    {% endblock %}
  </body>
</html>

twitter_backend/accounts/templates/accounts/profile.html
{% extends 'accounts/home.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home/style1.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/home/profile.css' %}" />
{% endblock %}


{% block main-header %}
<div class="main-section-header">
    <div class="home-header">
        <div class="shiva-profile">
            <img src="{% static 'images/shiva.png' %}" alt="shiva's profile" />
        </div>
        <h2 class="main-section-title">{{ request.user.username }}</h2>
    </div>
    <div class="top-tweets-icon">
        <img src="{% static 'images/stars.svg' %}" alt="top tweets icon" />
    </div>
</div>
{% endblock %}

{% block main-user-tweet %}
<main-profile>
    <div class="cover-photo-container">
        <div class="cover-photo">
            <img src="{{ logged_user.coverImage }}" alt="cover photo" />
        </div>
    </div>
    <div class="profile-container">
        <div class="edit-title-box">
            <div class="profile-image">
                <img src="{{ logged_user.profileImage }} " alt="profile photo" />
                <button class="edit-profile-button" onclick="togglePopupProfile()">Edit Profile</button>
            </div>
        </div>

        <div class="username-tag">
            <div class="display-name">{{ logged_user.display_name }}</div>
            <div class="username">@{{ logged_user.display_name}}</div>
        </div>
        <div class="profile-bio">
            {{ logged_user.bio }}
        </div>
        <div class="website" style="margin-top: 1rem;margin-bottom:1rem">
            <b style="font-weight: 700;">Website</b>{{ logged_user.website}}
        </div>
        <div class="joined-date">
            <div class="date-text">Joined Date</div>
            <div class="date" id="joined-date">{{logged_user.updated_at }}</div>
        </div>
    </div>
    <div class="follow-ing">
        <div class="posts tweet-flex">
            <div class="posts-count">{{posts|length}}</div>
            <div class="fin">Tweets</div>
        </div>
        <div class="retweets tweet-flex">
            <div class="following-count" style="margin-left:1px">{{retweets|length}}</div>
            <div class="fin">retweets</div>
        </div>
        <div class="followers tweet-flex">
            <div class="follow-count">{{followers|length}}</div>
            <div class="fin">Followers</div> 
        </div>
        <div class="following tweet-flex">
            <div class="following-count" style="margin-left:1px">{{following|length}}</div>
            <div class="fin">Following</div>
        </div>
    </div>
</main-profile>
{% endblock %}

{% block more-icon %}
<div class="more-icon" id="post-container-{{ tweet.uuid }}">
    <img src="{% static 'images/more-circle.svg' %}" alt="more icon" onclick="toggleDropdown(this)"/>
    <div id="dropdown-menu" class="dropdown-content">
        <a  onclick="openEditModal('{{tweet.uuid}}')" style="color: black;">Edit</a>
        <a href="" onclick="confirmDelete('{{tweet.uuid}}')">Delete</a>
    </div>
</div>

<div id="editModal" class="modal">
    <div class="modal-content popup">
        <span class="close" onclick="closeEditModal()">&times;</span>
        <form id="editForm" class="form" action="{% url 'accounts:update-tweet' tweet.uuid %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <!-- Textarea for content -->
            <textarea id="editContent" name="content" rows="4" cols="50"></textarea>
            <!-- Display area for the image -->
            <div id="imageDisplay"></div>
            <!-- File input for media -->
            <input type="file" id="editMedia" name="media" onchange="previewImage(this)">
            <button type="submit">Save Changes</button>
        </form>
    </div>
</div>
{% endblock %}

twitter_backend/accounts/templates/accounts/register.html
{% extends "accounts/login.html" %}

{% block title %}Sign up to Twitter{% endblock %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

{% block styles %}{% endblock %}

{% block body %}
<div class="container">
  <div class="header">
    <img src="https://img.icons8.com/color/48/000000/twitter.png" alt="Twitter Logo">
    <h2>Sign up to twitter</h2>
  </div>

  <div class="error">
    {% if error %}
    <p>{{error}}</p>
    {% endif %}
  </div>

  <div class="form">
    <form method="post" action="{% url 'accounts:register' %}">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username">
      <input type="email" name="email" placeholder="Email">
      <input type="password" name="password" placeholder="Password">
      <button type="submit">Sign up</button>
    </form>
  </div>

  <div class="footer">
    <a href="{% url 'accounts:login' %}">Already have an account? Log in</a>
  </div>
</div>
{% endblock %}